---
title: "About"
toc: true
---

## About Anna

Anna Ramji grew up hiking and fishing along the Eastern Sierra Nevada mountain range, where she developed an interest in ecology and the impacts of climate change on native ecosystems. She spent much of her childhood on Northern Californian beaches, developing a profound respect for the power, beauty, and importance of the Pacific Ocean. During her time as an undergraduate at the University of California, Berkeley, she worked as a research assistant and laboratory manager at Caldwell Laboratory, studying stomatopods and several species of octopus. Anna enjoyed taking extra-curricular courses in Data Science, Japanese, French, and Urban Design. She earned her Bachelor of Science degree in Environmental Sciences with a dual focus in Biology and Chemistry, graduating with Honors in 2021. She has since worked to co-author a <a href="https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0265292"> peer-reviewed paper </a> on body patterns of Octopus chierchiae with alumni from Caldwell Lab, which was published in PLOS One in April, 2023. 

Her interest in data science – particularly data visualization as a powerful tool for scientific communication – drew her to the Master of Environmental Data Science (MEDS) program at the Bren School of Environmental Science & Management. As a MEDS graduate student, she enjoyed combining her expertise in environmental issues with her passion for data science and visualization to become an enthusiastic and inclusive scientific communicator while maintaining a tidy and reproducible data science practice. She particularly enjoyed courses in Machine Learning, Data Management, Geospatial Analysis & Remote Sensing, and Data Visualization. In her [capstone project](https://bren.ucsb.edu/projects/identifying-priority-survey-sites-early-season-milkweed-conservation), she helped create a tool for researchers at the Santa Barbara Botanic Garden to plan surveys of milkweed species in the Los Padres National Forest for conservation efforts. Anna was the sole recipient of the faculty-nominated Academic Achievement Award in the MEDS class of 2024. 

She is interested in a wide range of sustainability-oriented topics, including agroecology, clean energy, and working with marine ecological data. Anna hopes to bring her environmental data science experience and passion for developing data-driven sustainable solutions to future roles. 

You can read more about her in her [2024 OHI Global Fellows interview](https://oceanhealthindex.org/news/2024-global-fellows/).


## Education:

Master of Environmental Data Science (MEDS), Bren School of Environmental Science & Management, University of California, Santa Barbara (2024)

B.S. Environmental Sciences, University of California, Berkeley (2021)

